### ISSUE TITLE
Add setup.py to the base repository 

### ISSUE THREAD

**Issue by djokester** [SangitaNLP/sangita#1]
setup.py is a python file, which usually tells you that the module/package you are about to install has been packaged and distributed with Distutils, which is the standard for distributing Python Modules.This allows you to easily install Python packages. Often it's enough to write:
`python setup.py install`
and the module will install itself.

Write the setup.py file for this package.

**Comment by vaibhavsingh97** [comment]
Claiming

**Comment by eulerkochy** [comment]
I am interested and wish to contribute to this project.

**Comment by djokester** [comment]
@vaibhavsingh97 did you work on this?

**Comment by vaibhavsingh97** [comment]
Yes, will send PR soon

**Comment by cseas** [comment]
Still open?

**Comment by djokester** [comment]
@cseas I guess I will work on this a bit later. Let this be as of now. Will be adding issues soon.

**Comment by djokester** [comment]
Has a direct dependency on  Issue #9
