### ISSUE TITLE
Improve the Lemmatizer

### ISSUE THREAD

**Issue by djokester** [SangitaNLP/sangita#11]

**Comment by Sylfrena** [comment]
Hey! I'd like to work on this issue. Is this up for grabs?

**Comment by djokester** [comment]
Hey! @tanvi15 is assigned this issue. 
I forgot to assign this to her. 
You can get another issue if you want.

**Comment by Sylfrena** [comment]
@djokester  Aukay! Um, so all issues have been claimed as of now.  Will you be adding more anytime soon? I am so sorry for being super late here(courtesy : exams) but I would love to work on this project. :)

**Comment by djokester** [comment]
Sure.
Join the slack channel for GSSoC if you are a GirlScript participant.
Or go ahead and join the slack channel for Sangita if you are a non-GSSoC
participant. Link in ReadMe
*Samriddhi Sinha*


*Technology Coordinator *
*Technology Student's Gymkhana*
*IIT Kharagpur.*

*| Website <http://www.samriddhisinha.in> | Quora
<https://www.quora.com/profile/Samriddhi-Sinha> | Facebook
<https://www.facebook.com/samriddhi.sinha.7> | LinkedIn
<https://www.linkedin.com/in/samriddhisinha/>*
