### ISSUE TITLE
Implement Sangita in Bengali

### ISSUE THREAD

**Issue by djokester** [SangitaNLP/sangita#14]
Task List for getting Started

- [ ] Implement Tokeniser for Bengali

- [ ] Find Datasets for the Language to move forward with.

**Comment by lavishsaluja** [comment]
Pretty good page of a person already working on the same thing: [https://www.isical.ac.in/~utpal/resources.php](ISI - UTPAL).
Not exactly what we want but kaggle has this bengaliAI group solving Bengali datasets for recognizing handwritten numeric digits in Bengali. [https://www.kaggle.com/BengaliAI/numta](Kaggle - BengaliAI)

**Comment by djokester** [comment]
@lavishsaluja good one
Lets connect at night.

**Comment by ighosh98** [comment]
Some other resources:
1. http://docs.cltk.org/en/latest/bengali.html
2. https://github.com/banglakit/awesome-bangla(It contains links to multiple datasets)
3. Handwritten Text in Bengali: https://data.mendeley.com/datasets/hf6sf8zrkc/2( May not exactly fit into the given specifications)
4. https://github.com/AtikRahman/Bangla_ABSA_Datasets Contains 2 excel files whose data has been used for sentiment analysis in some other project(License not added on Github)
