### ISSUE TITLE
Implement sangita in Telugu

### ISSUE THREAD

**Issue by sumanthd17** [SangitaNLP/sangita#18]
New language - Telugu

- [ ] Find Data corpus Telugu language. Add links in the comments to this Issue

- [ ] Implement tokenizer for Telugu

- [ ] Create a lemmentizer for Telugu

- [ ] Create a POS Tagger for Telugu.

**Comment by sumanthd17** [comment]
I'd like to work on this

**Comment by sumanthd17** [comment]
Corpus for telugu language can be found in this link.[TDIL](https://www.tdil-dc.in/index.php?option=com_download&task=showresourceDetails&toolid=1892&lang=en)

**Comment by djokester** [comment]
Kindly look for the original source of this dataset. 
TDIL tends to take open source licenses and make them closed source. So look for the original dataset for the resource. Also look for a few more datasets if possible.
