### ISSUE TITLE
Improve Upon the Idea Implemented in The Stemmer

### ISSUE THREAD

**Issue by djokester** [SangitaNLP/sangita#3]
Have look at the code in [stemmer.py](https://github.com/djokester/sangita/blob/master/sangita/hindi/stemmer.py)
Then do try to improve upon or provide an alternative pathway for that. 
Requirements: 
* Proficiency in Python. 
* Proficiency in Hindi and basic word inflections. 
* Knowledge of the different types of Stemmer. 

This issue involves three steps:
* Looking for appropriate data to help build rules for creating the stemmer. 
* Formulating linguistic rules for the stemmer. 
* Implementing the linguistic rules in code.

The pull request must contain detailed layout of how the developer sought to tackle the problem.
It must also contain the source of data and it's licensing specifications. Along with this there must be sufficient examples to demonstrate the working of the stemmer.

**Comment by djokester** [comment]
@cseas have a look at this.

**Comment by Naba7** [comment]
Can I be assigned this issue?
